spring:
  application:
    name: servicio-ventas
  profiles:
    active: dev

server:
  port: 8083

springdoc:
  api-docs:
    path: /servicio-ventas/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_pcfactory_dev?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/db_pcfactory_prod?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true